### ISSUE TITLE
Work on the corresponding website for TechEquilla: - Redesign the UI/UX of the website - Put in more animations 

### ISSUE THREAD

**Issue by PritikaSabharwal** [techequilla/community_app_boilerplate#16]
sir kindly assign this issue to me, our team, LogicWinners would like to work on this

**Comment by smaranjitghose** [comment]
@PritikaSabharwal, the current UI design is handled by @sakshi1499 and @sonalsk,

Please coordinate with them for adding more animations as you please, without having conflicts with the core codebase

**Comment by sakshi1499** [comment]
@PritikaSabharwal Hi! We have another suggestion on #8 so if you want to give your suggestions in, you are most welcome!

**Comment by smaranjitghose** [comment]
@PritikaSabharwal @sakshi1499  For the website please continue on its repo so that its easier to review the issues
