### ISSUE TITLE
Clean up the Flutter project

### ISSUE THREAD

**Issue by iamriya** [techequilla/community_app_boilerplate#2]
Certain files that should have not been in the git repo as mentioned in `.gitignore` are actually here resulting in the large size of the project. Is it possible to clean up the repo so that unnecessary files are not tracked?

**Comment by prasadsunny1** [comment]
You may try this.
https://www.git-tower.com/learn/git/faq/ignore-tracked-files-in-git

**Comment by prasadsunny1** [comment]
@iamriya if you think this issue is resolved then you can close this issue.
