### ISSUE TITLE
lib folder and main.dart file not found

### ISSUE THREAD

**Issue by khushbuThakker** [techequilla/community_app_boilerplate#30]
-In project, lib folder and main.dart file not found so not able to build the project.
-Font missing in asset folder but declared in pubspec.yaml file

__Please strictly follow the UI given and feel free to contact any of the mentors for help__

**Comment by smaranjitghose** [comment]
Khushbu, as we were working according to a completely new UI, I had removed the existing files that were for the GirlScript App Boilerplate. Could you create a blank flutter project with the dummy pages as specified in the UI  within the community_app_boilerplate and give a PR

**Comment by khushbuThakker** [comment]
Okay @smaranjitghose
